// resources/js/Components/Form.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  }>(),
  { method: "GET" }
);

const htmlMethods = ["GET", "POST"];
</script>

<template>
  <form :method="method === 'GET' ? method : 'POST'">
    <input
      v-if="method !== 'GET'"
      type="hidden"
      name="_token"
      :value="$page.props.csrfToken"
    />
    <input
      v-if="!htmlMethods.includes(method)"
      type="hidden"
      name="_method"
      :value="method"
    />

    <slot />
  </form>
</template>

// resources/js/Components/Form.tsx
import { AuthContext } from "@/context";
import { PropsWithChildren, useContext } from "react";

type FormProps = React.FormHTMLAttributes<HTMLFormElement> &
  PropsWithChildren<{
    method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  }>;

const htmlMethods = ["GET", "POST"];

export default function Form({ method = "GET", children, ...rest }: FormProps) {
  const { csrfToken } = useContext(AuthContext);
  return (
    <>
      <form method={method === "GET" ? method : "POST"} {...rest}>
        {method !== "GET" && (
          <input type="hidden" name="_token" value={csrfToken} />
        )}
        {!htmlMethods.includes(method) && (
          <input type="hidden" name="_method" value={method} />
        )}
        {children}
      </form>
    </>
  );
}
